### ISSUE TITLE
`./run usePrebuilt && ./run buildDebug` results in error 

### ISSUE THREAD

**Issue by leroycep** [erikarvstedt/nix-zig-build#1]
Hello, trying to use `./run usePrebuilt && ./run buildDebug` results in an error in the `buildDebug` step:

```console
[geemili@renvi:~/src/1_projects/nix-zig-build]$ src=/home/geemili/src/3_resources/zig ./run buildDebug
/tmp/zig-build/stage3/bin/zig build --prefix /tmp/zig-build/zig-debug --cache-dir /tmp/zig-build/zig-cache -Dconfig_h=/tmp/zig-build/config.h -Denable-llvm -Dno-lib 
/home/geemili/src/3_resources/zig/build.zig:42:17: error: expected type 'zig.CrossTarget', found 'zig.system.NativeTargetInfo'
        .target = b.host,
        ~~~~~~~~^~~~~~~~
/nix/store/d0d6xk5n9m6izjgl3ps99nh48mn0ls1g-zig-0.12.0-dev.1879+e19219fa0/lib/std/zig/system/NativeTargetInfo.zig:1:1: note: struct declared here
const std = @import("../../std.zig");
^~~~~
/nix/store/d0d6xk5n9m6izjgl3ps99nh48mn0ls1g-zig-0.12.0-dev.1879+e19219fa0/lib/std/zig/CrossTarget.zig:1:1: note: struct declared here
//! Contains all the same data as `Target`, additionally introducing the concept of "the native target".
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    runBuild__anon_6881: /nix/store/d0d6xk5n9m6izjgl3ps99nh48mn0ls1g-zig-0.12.0-dev.1879+e19219fa0/lib/std/Build.zig:1893:37
    steps__anon_6675: /nix/store/d0d6xk5n9m6izjgl3ps99nh48mn0ls1g-zig-0.12.0-dev.1879+e19219fa0/lib/build_runner.zig:969:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
./run: line 109: pop_var_context: head of shell_variables not a function context
./run: line 80: pop_var_context: head of shell_variables not a function context
./run: line 216: pop_var_context: head of shell_variables not a function context
```

I think this is because of recent changes to the standard library. Setting `--zig-lib-dir` to point to `$src/lib/std` might fix it? Will report back when I have the time to try it out.

**Comment by erikarvstedt** [comment]
Thanks!
My daily repo update ran at 13:00 UTC so it didn't yet catch the latest update to Zig master.
[Fixed here](https://github.com/erikarvstedt/nix-zig-build/commit/90856678d1e214b9ab0562b7e5c26c5233b32b77).

FYI, the reason why your build failed was that the prebuilt Zig binary wasn't yet updated to master.
`buildBootstrap` would have worked.

**Comment by erikarvstedt** [comment]
You're right, the prebuilt stage3 didn't pick up the Zig lib from the src.
Using the Zig lib from the src was the intended behavior and I made sure to check it with `strace`, but somehow this bug slipped through.
[Fixed here](https://github.com/erikarvstedt/nix-zig-build/commit/f1faf8f74cb838f3337544019437ac43d399bef2).

(But even with this fix your build would have failed because build related cmdline args have changed in latest Zig binary 😸.)
